from manim import *
import numpy as np

class TeachingScene(Scene):
    def setup_layout(self, title_text, lecture_lines):
        # BASE
        self.camera.background_color = "#000000"
        self.title = Text(title_text, font_size=28, color=WHITE).to_edge(UP)
        self.add(self.title)

        # Left-side lecture content (bullets with "-")
        lecture_texts = [Text(line, font_size=22, color=WHITE) for line in lecture_lines]
        self.lecture = VGroup(*lecture_texts).arrange(DOWN, aligned_edge=LEFT).scale(0.8)
        self.lecture.to_edge(LEFT, buff=0.2)
        self.add(self.lecture)

        # Define fine-grained animation grid (4x4 grid on right side)
        self.grid = {}
        rows = ["A", "B", "C", "D", "E", "F"]  # Top to bottom
        cols = ["1", "2", "3", "4", "5", "6"]  # Left to right

        for i, row in enumerate(rows):
            for j, col in enumerate(cols):
                x = 0.5 + j * 1
                y = 2.2 - i * 1
                self.grid[f"{row}{col}"] = np.array([x, y, 0])

    def place_at_grid(self, mobject, grid_pos, scale_factor=1.0):
        mobject.scale(scale_factor)
        mobject.move_to(self.grid[grid_pos])
        return mobject

    def place_in_area(self, mobject, top_left, bottom_right, scale_factor=1.0):
        tl_pos = self.grid[top_left]
        br_pos = self.grid[bottom_right]
        
        # Calculate center of the area
        center_x = (tl_pos[0] + br_pos[0]) / 2
        center_y = (tl_pos[1] + br_pos[1]) / 2
        center = np.array([center_x, center_y, 0])
        
        mobject.scale(scale_factor)
        mobject.move_to(center)
        return mobject

class Section3Scene(TeachingScene):
    def construct(self):
        lecture_lines = [
            "The Brachistochrone curve is a cycloid.",
            "Traced by a point on a rolling circle.",
            "It balances distance and speed perfectly.",
            "Accelerate rapidly, then cruise to B.",
            "This is the fastest possible path."
        ]
        self.setup_layout("The Solution: The Cycloid", lecture_lines)
        
        r = 0.4
        
        # --- Animation for Lecture Line 1 ---
        # Display a cycloid curve generated by a rolling circle. (Color: #1ABC9C)
        self.play(self.lecture[0].animate.set_color("#1ABC9C"))
        
        # --- Animation for Lecture Line 2 ---
        # Animate the circle rolling along a horizontal line. (Color: #FFFFFF)
        self.play(self.lecture[1].animate.set_color("#FFFFFF"))
        
        # --- Animation for Lecture Line 3 ---
        # Trace the path of a point on the circle's edge. (Color: #3498DB)
        self.play(self.lecture[2].animate.set_color("#3498DB"))
        
        # --- Animation for Lecture Line 4 ---
        # Highlight the cycloid path as the fastest route. (Color: #E74C3C)
        self.play(self.lecture[3].animate.set_color("#E74C3C"))
        
        # --- Animation for Lecture Line 5 ---
        # Show the cycloid equation: x = r(θ - sinθ), y = r(1 - cosθ). (Color: #F1C40F)
        self.play(self.lecture[4].animate.set_color("#F1C40F"))
        
        # Visuals
        circle = SVGMobject("/scratch/pawsey1357/jthen/Code2Video/assets/icon/circle.svg", color=WHITE)
        circle.set_height(r * 2)
        
        # Cycloid Path
        def cycloid_func(t):
            return np.array([r * (t - np.sin(t)), -r * (1 - np.cos(t)), 0])
        
        cycloid = ParametricFunction(cycloid_func, t_range=[0, 2*PI], color="#1ABC9C")
        
        # Point on rim
        dot = Dot(color="#3498DB")
        
        # Rolling animation
        line = Line(start=self.grid['B1'], end=self.grid['B6'], color=WHITE)
        
        # Group visuals
        visuals = VGroup(circle, cycloid, dot, line)
        
        # Re-positioning per critique
        self.place_in_area(visuals, 'A3', 'C6', scale_factor=0.9)
        
        self.add(line, cycloid, circle, dot)
        
        # Use value tracker to animate
        theta = ValueTracker(0)
        
        def update_circle(c):
            t = theta.get_value()
            c.move_to(np.array([2.5 + r * t, 0.0, 0])) # Adjusted based on new position
            
        def update_dot(d):
            t = theta.get_value()
            d.move_to(np.array([2.5 + r * t + r * np.sin(t), 0.0 - r * np.cos(t), 0]))
            
        circle.add_updater(update_circle)
        dot.add_updater(update_dot)
        
        self.play(theta.animate.set_value(2 * PI), run_time=4, rate_func=linear)
        
        # Equation
        eq = MathTex("x = r(\\theta - \\sin\\theta), \\quad y = r(1 - \\cos\\theta)", color="#F1C40F")
        self.place_in_area(eq, 'D3', 'E6', scale_factor=0.7)
        self.play(Write(eq))
        
        self.wait(2)
